// Generated by ProtoGen, Version=2.4.1.521, Culture=neutral, PublicKeyToken=55f7125234beb589.  DO NOT EDIT!
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.ProtocolBuffers;
using pbc = global::Google.ProtocolBuffers.Collections;
using pbd = global::Google.ProtocolBuffers.Descriptors;
using scg = global::System.Collections.Generic;
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
public static partial class ConversationProtobuf {

  #region Extension registration
  public static void RegisterAllExtensions(pb::ExtensionRegistry registry) {
  }
  #endregion
  #region Static variables
  internal static pbd::MessageDescriptor internal__static_ConversationPackage__Descriptor;
  internal static pb::FieldAccess.FieldAccessorTable<global::ConversationPackage, global::ConversationPackage.Builder> internal__static_ConversationPackage__FieldAccessorTable;
  internal static pbd::MessageDescriptor internal__static_Conversation__Descriptor;
  internal static pb::FieldAccess.FieldAccessorTable<global::Conversation, global::Conversation.Builder> internal__static_Conversation__FieldAccessorTable;
  internal static pbd::MessageDescriptor internal__static_ConversationNode__Descriptor;
  internal static pb::FieldAccess.FieldAccessorTable<global::ConversationNode, global::ConversationNode.Builder> internal__static_ConversationNode__FieldAccessorTable;
  internal static pbd::MessageDescriptor internal__static_Connection__Descriptor;
  internal static pb::FieldAccess.FieldAccessorTable<global::Connection, global::Connection.Builder> internal__static_Connection__FieldAccessorTable;
  internal static pbd::MessageDescriptor internal__static_RequirementSet__Descriptor;
  internal static pb::FieldAccess.FieldAccessorTable<global::RequirementSet, global::RequirementSet.Builder> internal__static_RequirementSet__FieldAccessorTable;
  #endregion
  #region Descriptor
  public static pbd::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbd::FileDescriptor descriptor;
  
  static ConversationProtobuf() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        "ChpDb252ZXJzYXRpb25Qcm90b2J1Zi5wcm90bxoTUXVlc3RQcm90b2J1Zi5w" + 
        "cm90byI7ChNDb252ZXJzYXRpb25QYWNrYWdlEiQKDWNvbnZlcnNhdGlvbnMY" + 
        "ASADKAsyDS5Db252ZXJzYXRpb24iUgoMQ29udmVyc2F0aW9uEiMKCGFsbE5v" + 
        "ZGVzGAEgAygLMhEuQ29udmVyc2F0aW9uTm9kZRIMCgRuYW1lGAIgASgJEg8K" + 
        "B2NyZWF0b3IYAyABKAkiiwEKEENvbnZlcnNhdGlvbk5vZGUSDAoEdGV4dBgB" + 
        "IAIoCRILCgN1aWQYAiACKAMSCQoBWBgDIAIoBRIJCgFZGAQgAigFEiAKC2Nv" + 
        "bm5lY3Rpb25zGAUgAygLMgsuQ29ubmVjdGlvbhIkCgZibG9ja3MYBiADKAsy" + 
        "FC5TdGF0dXNCbG9ja1Byb3RvY29sIlQKCkNvbm5lY3Rpb24SDgoGbm9kZUlk" + 
        "GAEgAigDEgwKBHRleHQYAiACKAkSKAoPcmVxdWlyZW1lbnRTZXRzGAMgAygL" + 
        "Mg8uUmVxdWlyZW1lbnRTZXQiQAoOUmVxdWlyZW1lbnRTZXQSLgoMcmVxdWly" + 
        "ZW1lbnRzGAEgAygLMhguU3RhdHVzQ2hlY2thYmxlUHJvdG9jb2xCIQofc3Rz" + 
        "cXVlc3RidWlsZGVyLnByb3RvY29sYnVmZmVycw==");
    pbd::FileDescriptor.InternalDescriptorAssigner assigner = delegate(pbd::FileDescriptor root) {
      descriptor = root;
      internal__static_ConversationPackage__Descriptor = Descriptor.MessageTypes[0];
      internal__static_ConversationPackage__FieldAccessorTable = 
          new pb::FieldAccess.FieldAccessorTable<global::ConversationPackage, global::ConversationPackage.Builder>(internal__static_ConversationPackage__Descriptor,
              new string[] { "Conversations", });
      internal__static_Conversation__Descriptor = Descriptor.MessageTypes[1];
      internal__static_Conversation__FieldAccessorTable = 
          new pb::FieldAccess.FieldAccessorTable<global::Conversation, global::Conversation.Builder>(internal__static_Conversation__Descriptor,
              new string[] { "AllNodes", "Name", "Creator", });
      internal__static_ConversationNode__Descriptor = Descriptor.MessageTypes[2];
      internal__static_ConversationNode__FieldAccessorTable = 
          new pb::FieldAccess.FieldAccessorTable<global::ConversationNode, global::ConversationNode.Builder>(internal__static_ConversationNode__Descriptor,
              new string[] { "Text", "Uid", "X", "Y", "Connections", "Blocks", });
      internal__static_Connection__Descriptor = Descriptor.MessageTypes[3];
      internal__static_Connection__FieldAccessorTable = 
          new pb::FieldAccess.FieldAccessorTable<global::Connection, global::Connection.Builder>(internal__static_Connection__Descriptor,
              new string[] { "NodeId", "Text", "RequirementSets", });
      internal__static_RequirementSet__Descriptor = Descriptor.MessageTypes[4];
      internal__static_RequirementSet__FieldAccessorTable = 
          new pb::FieldAccess.FieldAccessorTable<global::RequirementSet, global::RequirementSet.Builder>(internal__static_RequirementSet__Descriptor,
              new string[] { "Requirements", });
      return null;
    };
    pbd::FileDescriptor.InternalBuildGeneratedFileFrom(descriptorData,
        new pbd::FileDescriptor[] {
        global::QuestProtobuf.Descriptor, 
        }, assigner);
  }
  #endregion
  
}
#region Messages
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
public sealed partial class ConversationPackage : pb::GeneratedMessage<ConversationPackage, ConversationPackage.Builder> {
  private ConversationPackage() { }
  private static readonly ConversationPackage defaultInstance = new ConversationPackage().MakeReadOnly();
  private static readonly string[] _conversationPackageFieldNames = new string[] { "conversations" };
  private static readonly uint[] _conversationPackageFieldTags = new uint[] { 10 };
  public static ConversationPackage DefaultInstance {
    get { return defaultInstance; }
  }
  
  public override ConversationPackage DefaultInstanceForType {
    get { return DefaultInstance; }
  }
  
  protected override ConversationPackage ThisMessage {
    get { return this; }
  }
  
  public static pbd::MessageDescriptor Descriptor {
    get { return global::ConversationProtobuf.internal__static_ConversationPackage__Descriptor; }
  }
  
  protected override pb::FieldAccess.FieldAccessorTable<ConversationPackage, ConversationPackage.Builder> InternalFieldAccessors {
    get { return global::ConversationProtobuf.internal__static_ConversationPackage__FieldAccessorTable; }
  }
  
  public const int ConversationsFieldNumber = 1;
  private pbc::PopsicleList<global::Conversation> conversations_ = new pbc::PopsicleList<global::Conversation>();
  public scg::IList<global::Conversation> ConversationsList {
    get { return conversations_; }
  }
  public int ConversationsCount {
    get { return conversations_.Count; }
  }
  public global::Conversation GetConversations(int index) {
    return conversations_[index];
  }
  
  public override bool IsInitialized {
    get {
      foreach (global::Conversation element in ConversationsList) {
        if (!element.IsInitialized) return false;
      }
      return true;
    }
  }
  
  public override void WriteTo(pb::ICodedOutputStream output) {
    int size = SerializedSize;
    string[] field_names = _conversationPackageFieldNames;
    if (conversations_.Count > 0) {
      output.WriteMessageArray(1, field_names[0], conversations_);
    }
    UnknownFields.WriteTo(output);
  }
  
  private int memoizedSerializedSize = -1;
  public override int SerializedSize {
    get {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
      
      size = 0;
      foreach (global::Conversation element in ConversationsList) {
        size += pb::CodedOutputStream.ComputeMessageSize(1, element);
      }
      size += UnknownFields.SerializedSize;
      memoizedSerializedSize = size;
      return size;
    }
  }
  
  public static ConversationPackage ParseFrom(pb::ByteString data) {
    return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
  }
  public static ConversationPackage ParseFrom(pb::ByteString data, pb::ExtensionRegistry extensionRegistry) {
    return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
  }
  public static ConversationPackage ParseFrom(byte[] data) {
    return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
  }
  public static ConversationPackage ParseFrom(byte[] data, pb::ExtensionRegistry extensionRegistry) {
    return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
  }
  public static ConversationPackage ParseFrom(global::System.IO.Stream input) {
    return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
  }
  public static ConversationPackage ParseFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
    return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
  }
  public static ConversationPackage ParseDelimitedFrom(global::System.IO.Stream input) {
    return CreateBuilder().MergeDelimitedFrom(input).BuildParsed();
  }
  public static ConversationPackage ParseDelimitedFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
    return CreateBuilder().MergeDelimitedFrom(input, extensionRegistry).BuildParsed();
  }
  public static ConversationPackage ParseFrom(pb::ICodedInputStream input) {
    return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
  }
  public static ConversationPackage ParseFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
    return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
  }
  private ConversationPackage MakeReadOnly() {
    conversations_.MakeReadOnly();
    return this;
  }
  
  public static Builder CreateBuilder() { return new Builder(); }
  public override Builder ToBuilder() { return CreateBuilder(this); }
  public override Builder CreateBuilderForType() { return new Builder(); }
  public static Builder CreateBuilder(ConversationPackage prototype) {
    return new Builder(prototype);
  }
  
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class Builder : pb::GeneratedBuilder<ConversationPackage, Builder> {
    protected override Builder ThisBuilder {
      get { return this; }
    }
    public Builder() {
      result = DefaultInstance;
      resultIsReadOnly = true;
    }
    internal Builder(ConversationPackage cloneFrom) {
      result = cloneFrom;
      resultIsReadOnly = true;
    }
    
    private bool resultIsReadOnly;
    private ConversationPackage result;
    
    private ConversationPackage PrepareBuilder() {
      if (resultIsReadOnly) {
        ConversationPackage original = result;
        result = new ConversationPackage();
        resultIsReadOnly = false;
        MergeFrom(original);
      }
      return result;
    }
    
    public override bool IsInitialized {
      get { return result.IsInitialized; }
    }
    
    protected override ConversationPackage MessageBeingBuilt {
      get { return PrepareBuilder(); }
    }
    
    public override Builder Clear() {
      result = DefaultInstance;
      resultIsReadOnly = true;
      return this;
    }
    
    public override Builder Clone() {
      if (resultIsReadOnly) {
        return new Builder(result);
      } else {
        return new Builder().MergeFrom(result);
      }
    }
    
    public override pbd::MessageDescriptor DescriptorForType {
      get { return global::ConversationPackage.Descriptor; }
    }
    
    public override ConversationPackage DefaultInstanceForType {
      get { return global::ConversationPackage.DefaultInstance; }
    }
    
    public override ConversationPackage BuildPartial() {
      if (resultIsReadOnly) {
        return result;
      }
      resultIsReadOnly = true;
      return result.MakeReadOnly();
    }
    
    public override Builder MergeFrom(pb::IMessage other) {
      if (other is ConversationPackage) {
        return MergeFrom((ConversationPackage) other);
      } else {
        base.MergeFrom(other);
        return this;
      }
    }
    
    public override Builder MergeFrom(ConversationPackage other) {
      if (other == global::ConversationPackage.DefaultInstance) return this;
      PrepareBuilder();
      if (other.conversations_.Count != 0) {
        result.conversations_.Add(other.conversations_);
      }
      this.MergeUnknownFields(other.UnknownFields);
      return this;
    }
    
    public override Builder MergeFrom(pb::ICodedInputStream input) {
      return MergeFrom(input, pb::ExtensionRegistry.Empty);
    }
    
    public override Builder MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
      PrepareBuilder();
      pb::UnknownFieldSet.Builder unknownFields = null;
      uint tag;
      string field_name;
      while (input.ReadTag(out tag, out field_name)) {
        if(tag == 0 && field_name != null) {
          int field_ordinal = global::System.Array.BinarySearch(_conversationPackageFieldNames, field_name, global::System.StringComparer.Ordinal);
          if(field_ordinal >= 0)
            tag = _conversationPackageFieldTags[field_ordinal];
          else {
            if (unknownFields == null) {
              unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
            }
            ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
            continue;
          }
        }
        switch (tag) {
          case 0: {
            throw pb::InvalidProtocolBufferException.InvalidTag();
          }
          default: {
            if (pb::WireFormat.IsEndGroupTag(tag)) {
              if (unknownFields != null) {
                this.UnknownFields = unknownFields.Build();
              }
              return this;
            }
            if (unknownFields == null) {
              unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
            }
            ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
            break;
          }
          case 10: {
            input.ReadMessageArray(tag, field_name, result.conversations_, global::Conversation.DefaultInstance, extensionRegistry);
            break;
          }
        }
      }
      
      if (unknownFields != null) {
        this.UnknownFields = unknownFields.Build();
      }
      return this;
    }
    
    
    public pbc::IPopsicleList<global::Conversation> ConversationsList {
      get { return PrepareBuilder().conversations_; }
    }
    public int ConversationsCount {
      get { return result.ConversationsCount; }
    }
    public global::Conversation GetConversations(int index) {
      return result.GetConversations(index);
    }
    public Builder SetConversations(int index, global::Conversation value) {
      pb::ThrowHelper.ThrowIfNull(value, "value");
      PrepareBuilder();
      result.conversations_[index] = value;
      return this;
    }
    public Builder SetConversations(int index, global::Conversation.Builder builderForValue) {
      pb::ThrowHelper.ThrowIfNull(builderForValue, "builderForValue");
      PrepareBuilder();
      result.conversations_[index] = builderForValue.Build();
      return this;
    }
    public Builder AddConversations(global::Conversation value) {
      pb::ThrowHelper.ThrowIfNull(value, "value");
      PrepareBuilder();
      result.conversations_.Add(value);
      return this;
    }
    public Builder AddConversations(global::Conversation.Builder builderForValue) {
      pb::ThrowHelper.ThrowIfNull(builderForValue, "builderForValue");
      PrepareBuilder();
      result.conversations_.Add(builderForValue.Build());
      return this;
    }
    public Builder AddRangeConversations(scg::IEnumerable<global::Conversation> values) {
      PrepareBuilder();
      result.conversations_.Add(values);
      return this;
    }
    public Builder ClearConversations() {
      PrepareBuilder();
      result.conversations_.Clear();
      return this;
    }
  }
  static ConversationPackage() {
    object.ReferenceEquals(global::ConversationProtobuf.Descriptor, null);
  }
}

[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
public sealed partial class Conversation : pb::GeneratedMessage<Conversation, Conversation.Builder> {
  private Conversation() { }
  private static readonly Conversation defaultInstance = new Conversation().MakeReadOnly();
  private static readonly string[] _conversationFieldNames = new string[] { "allNodes", "creator", "name" };
  private static readonly uint[] _conversationFieldTags = new uint[] { 10, 26, 18 };
  public static Conversation DefaultInstance {
    get { return defaultInstance; }
  }
  
  public override Conversation DefaultInstanceForType {
    get { return DefaultInstance; }
  }
  
  protected override Conversation ThisMessage {
    get { return this; }
  }
  
  public static pbd::MessageDescriptor Descriptor {
    get { return global::ConversationProtobuf.internal__static_Conversation__Descriptor; }
  }
  
  protected override pb::FieldAccess.FieldAccessorTable<Conversation, Conversation.Builder> InternalFieldAccessors {
    get { return global::ConversationProtobuf.internal__static_Conversation__FieldAccessorTable; }
  }
  
  public const int AllNodesFieldNumber = 1;
  private pbc::PopsicleList<global::ConversationNode> allNodes_ = new pbc::PopsicleList<global::ConversationNode>();
  public scg::IList<global::ConversationNode> AllNodesList {
    get { return allNodes_; }
  }
  public int AllNodesCount {
    get { return allNodes_.Count; }
  }
  public global::ConversationNode GetAllNodes(int index) {
    return allNodes_[index];
  }
  
  public const int NameFieldNumber = 2;
  private bool hasName;
  private string name_ = "";
  public bool HasName {
    get { return hasName; }
  }
  public string Name {
    get { return name_; }
  }
  
  public const int CreatorFieldNumber = 3;
  private bool hasCreator;
  private string creator_ = "";
  public bool HasCreator {
    get { return hasCreator; }
  }
  public string Creator {
    get { return creator_; }
  }
  
  public override bool IsInitialized {
    get {
      foreach (global::ConversationNode element in AllNodesList) {
        if (!element.IsInitialized) return false;
      }
      return true;
    }
  }
  
  public override void WriteTo(pb::ICodedOutputStream output) {
    int size = SerializedSize;
    string[] field_names = _conversationFieldNames;
    if (allNodes_.Count > 0) {
      output.WriteMessageArray(1, field_names[0], allNodes_);
    }
    if (hasName) {
      output.WriteString(2, field_names[2], Name);
    }
    if (hasCreator) {
      output.WriteString(3, field_names[1], Creator);
    }
    UnknownFields.WriteTo(output);
  }
  
  private int memoizedSerializedSize = -1;
  public override int SerializedSize {
    get {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
      
      size = 0;
      foreach (global::ConversationNode element in AllNodesList) {
        size += pb::CodedOutputStream.ComputeMessageSize(1, element);
      }
      if (hasName) {
        size += pb::CodedOutputStream.ComputeStringSize(2, Name);
      }
      if (hasCreator) {
        size += pb::CodedOutputStream.ComputeStringSize(3, Creator);
      }
      size += UnknownFields.SerializedSize;
      memoizedSerializedSize = size;
      return size;
    }
  }
  
  public static Conversation ParseFrom(pb::ByteString data) {
    return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
  }
  public static Conversation ParseFrom(pb::ByteString data, pb::ExtensionRegistry extensionRegistry) {
    return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
  }
  public static Conversation ParseFrom(byte[] data) {
    return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
  }
  public static Conversation ParseFrom(byte[] data, pb::ExtensionRegistry extensionRegistry) {
    return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
  }
  public static Conversation ParseFrom(global::System.IO.Stream input) {
    return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
  }
  public static Conversation ParseFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
    return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
  }
  public static Conversation ParseDelimitedFrom(global::System.IO.Stream input) {
    return CreateBuilder().MergeDelimitedFrom(input).BuildParsed();
  }
  public static Conversation ParseDelimitedFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
    return CreateBuilder().MergeDelimitedFrom(input, extensionRegistry).BuildParsed();
  }
  public static Conversation ParseFrom(pb::ICodedInputStream input) {
    return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
  }
  public static Conversation ParseFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
    return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
  }
  private Conversation MakeReadOnly() {
    allNodes_.MakeReadOnly();
    return this;
  }
  
  public static Builder CreateBuilder() { return new Builder(); }
  public override Builder ToBuilder() { return CreateBuilder(this); }
  public override Builder CreateBuilderForType() { return new Builder(); }
  public static Builder CreateBuilder(Conversation prototype) {
    return new Builder(prototype);
  }
  
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class Builder : pb::GeneratedBuilder<Conversation, Builder> {
    protected override Builder ThisBuilder {
      get { return this; }
    }
    public Builder() {
      result = DefaultInstance;
      resultIsReadOnly = true;
    }
    internal Builder(Conversation cloneFrom) {
      result = cloneFrom;
      resultIsReadOnly = true;
    }
    
    private bool resultIsReadOnly;
    private Conversation result;
    
    private Conversation PrepareBuilder() {
      if (resultIsReadOnly) {
        Conversation original = result;
        result = new Conversation();
        resultIsReadOnly = false;
        MergeFrom(original);
      }
      return result;
    }
    
    public override bool IsInitialized {
      get { return result.IsInitialized; }
    }
    
    protected override Conversation MessageBeingBuilt {
      get { return PrepareBuilder(); }
    }
    
    public override Builder Clear() {
      result = DefaultInstance;
      resultIsReadOnly = true;
      return this;
    }
    
    public override Builder Clone() {
      if (resultIsReadOnly) {
        return new Builder(result);
      } else {
        return new Builder().MergeFrom(result);
      }
    }
    
    public override pbd::MessageDescriptor DescriptorForType {
      get { return global::Conversation.Descriptor; }
    }
    
    public override Conversation DefaultInstanceForType {
      get { return global::Conversation.DefaultInstance; }
    }
    
    public override Conversation BuildPartial() {
      if (resultIsReadOnly) {
        return result;
      }
      resultIsReadOnly = true;
      return result.MakeReadOnly();
    }
    
    public override Builder MergeFrom(pb::IMessage other) {
      if (other is Conversation) {
        return MergeFrom((Conversation) other);
      } else {
        base.MergeFrom(other);
        return this;
      }
    }
    
    public override Builder MergeFrom(Conversation other) {
      if (other == global::Conversation.DefaultInstance) return this;
      PrepareBuilder();
      if (other.allNodes_.Count != 0) {
        result.allNodes_.Add(other.allNodes_);
      }
      if (other.HasName) {
        Name = other.Name;
      }
      if (other.HasCreator) {
        Creator = other.Creator;
      }
      this.MergeUnknownFields(other.UnknownFields);
      return this;
    }
    
    public override Builder MergeFrom(pb::ICodedInputStream input) {
      return MergeFrom(input, pb::ExtensionRegistry.Empty);
    }
    
    public override Builder MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
      PrepareBuilder();
      pb::UnknownFieldSet.Builder unknownFields = null;
      uint tag;
      string field_name;
      while (input.ReadTag(out tag, out field_name)) {
        if(tag == 0 && field_name != null) {
          int field_ordinal = global::System.Array.BinarySearch(_conversationFieldNames, field_name, global::System.StringComparer.Ordinal);
          if(field_ordinal >= 0)
            tag = _conversationFieldTags[field_ordinal];
          else {
            if (unknownFields == null) {
              unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
            }
            ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
            continue;
          }
        }
        switch (tag) {
          case 0: {
            throw pb::InvalidProtocolBufferException.InvalidTag();
          }
          default: {
            if (pb::WireFormat.IsEndGroupTag(tag)) {
              if (unknownFields != null) {
                this.UnknownFields = unknownFields.Build();
              }
              return this;
            }
            if (unknownFields == null) {
              unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
            }
            ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
            break;
          }
          case 10: {
            input.ReadMessageArray(tag, field_name, result.allNodes_, global::ConversationNode.DefaultInstance, extensionRegistry);
            break;
          }
          case 18: {
            result.hasName = input.ReadString(ref result.name_);
            break;
          }
          case 26: {
            result.hasCreator = input.ReadString(ref result.creator_);
            break;
          }
        }
      }
      
      if (unknownFields != null) {
        this.UnknownFields = unknownFields.Build();
      }
      return this;
    }
    
    
    public pbc::IPopsicleList<global::ConversationNode> AllNodesList {
      get { return PrepareBuilder().allNodes_; }
    }
    public int AllNodesCount {
      get { return result.AllNodesCount; }
    }
    public global::ConversationNode GetAllNodes(int index) {
      return result.GetAllNodes(index);
    }
    public Builder SetAllNodes(int index, global::ConversationNode value) {
      pb::ThrowHelper.ThrowIfNull(value, "value");
      PrepareBuilder();
      result.allNodes_[index] = value;
      return this;
    }
    public Builder SetAllNodes(int index, global::ConversationNode.Builder builderForValue) {
      pb::ThrowHelper.ThrowIfNull(builderForValue, "builderForValue");
      PrepareBuilder();
      result.allNodes_[index] = builderForValue.Build();
      return this;
    }
    public Builder AddAllNodes(global::ConversationNode value) {
      pb::ThrowHelper.ThrowIfNull(value, "value");
      PrepareBuilder();
      result.allNodes_.Add(value);
      return this;
    }
    public Builder AddAllNodes(global::ConversationNode.Builder builderForValue) {
      pb::ThrowHelper.ThrowIfNull(builderForValue, "builderForValue");
      PrepareBuilder();
      result.allNodes_.Add(builderForValue.Build());
      return this;
    }
    public Builder AddRangeAllNodes(scg::IEnumerable<global::ConversationNode> values) {
      PrepareBuilder();
      result.allNodes_.Add(values);
      return this;
    }
    public Builder ClearAllNodes() {
      PrepareBuilder();
      result.allNodes_.Clear();
      return this;
    }
    
    public bool HasName {
      get { return result.hasName; }
    }
    public string Name {
      get { return result.Name; }
      set { SetName(value); }
    }
    public Builder SetName(string value) {
      pb::ThrowHelper.ThrowIfNull(value, "value");
      PrepareBuilder();
      result.hasName = true;
      result.name_ = value;
      return this;
    }
    public Builder ClearName() {
      PrepareBuilder();
      result.hasName = false;
      result.name_ = "";
      return this;
    }
    
    public bool HasCreator {
      get { return result.hasCreator; }
    }
    public string Creator {
      get { return result.Creator; }
      set { SetCreator(value); }
    }
    public Builder SetCreator(string value) {
      pb::ThrowHelper.ThrowIfNull(value, "value");
      PrepareBuilder();
      result.hasCreator = true;
      result.creator_ = value;
      return this;
    }
    public Builder ClearCreator() {
      PrepareBuilder();
      result.hasCreator = false;
      result.creator_ = "";
      return this;
    }
  }
  static Conversation() {
    object.ReferenceEquals(global::ConversationProtobuf.Descriptor, null);
  }
}

[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
public sealed partial class ConversationNode : pb::GeneratedMessage<ConversationNode, ConversationNode.Builder> {
  private ConversationNode() { }
  private static readonly ConversationNode defaultInstance = new ConversationNode().MakeReadOnly();
  private static readonly string[] _conversationNodeFieldNames = new string[] { "X", "Y", "blocks", "connections", "text", "uid" };
  private static readonly uint[] _conversationNodeFieldTags = new uint[] { 24, 32, 50, 42, 10, 16 };
  public static ConversationNode DefaultInstance {
    get { return defaultInstance; }
  }
  
  public override ConversationNode DefaultInstanceForType {
    get { return DefaultInstance; }
  }
  
  protected override ConversationNode ThisMessage {
    get { return this; }
  }
  
  public static pbd::MessageDescriptor Descriptor {
    get { return global::ConversationProtobuf.internal__static_ConversationNode__Descriptor; }
  }
  
  protected override pb::FieldAccess.FieldAccessorTable<ConversationNode, ConversationNode.Builder> InternalFieldAccessors {
    get { return global::ConversationProtobuf.internal__static_ConversationNode__FieldAccessorTable; }
  }
  
  public const int TextFieldNumber = 1;
  private bool hasText;
  private string text_ = "";
  public bool HasText {
    get { return hasText; }
  }
  public string Text {
    get { return text_; }
  }
  
  public const int UidFieldNumber = 2;
  private bool hasUid;
  private long uid_;
  public bool HasUid {
    get { return hasUid; }
  }
  public long Uid {
    get { return uid_; }
  }
  
  public const int XFieldNumber = 3;
  private bool hasX;
  private int x_;
  public bool HasX {
    get { return hasX; }
  }
  public int X {
    get { return x_; }
  }
  
  public const int YFieldNumber = 4;
  private bool hasY;
  private int y_;
  public bool HasY {
    get { return hasY; }
  }
  public int Y {
    get { return y_; }
  }
  
  public const int ConnectionsFieldNumber = 5;
  private pbc::PopsicleList<global::Connection> connections_ = new pbc::PopsicleList<global::Connection>();
  public scg::IList<global::Connection> ConnectionsList {
    get { return connections_; }
  }
  public int ConnectionsCount {
    get { return connections_.Count; }
  }
  public global::Connection GetConnections(int index) {
    return connections_[index];
  }
  
  public const int BlocksFieldNumber = 6;
  private pbc::PopsicleList<global::StatusBlockProtocol> blocks_ = new pbc::PopsicleList<global::StatusBlockProtocol>();
  public scg::IList<global::StatusBlockProtocol> BlocksList {
    get { return blocks_; }
  }
  public int BlocksCount {
    get { return blocks_.Count; }
  }
  public global::StatusBlockProtocol GetBlocks(int index) {
    return blocks_[index];
  }
  
  public override bool IsInitialized {
    get {
      if (!hasText) return false;
      if (!hasUid) return false;
      if (!hasX) return false;
      if (!hasY) return false;
      foreach (global::Connection element in ConnectionsList) {
        if (!element.IsInitialized) return false;
      }
      foreach (global::StatusBlockProtocol element in BlocksList) {
        if (!element.IsInitialized) return false;
      }
      return true;
    }
  }
  
  public override void WriteTo(pb::ICodedOutputStream output) {
    int size = SerializedSize;
    string[] field_names = _conversationNodeFieldNames;
    if (hasText) {
      output.WriteString(1, field_names[4], Text);
    }
    if (hasUid) {
      output.WriteInt64(2, field_names[5], Uid);
    }
    if (hasX) {
      output.WriteInt32(3, field_names[0], X);
    }
    if (hasY) {
      output.WriteInt32(4, field_names[1], Y);
    }
    if (connections_.Count > 0) {
      output.WriteMessageArray(5, field_names[3], connections_);
    }
    if (blocks_.Count > 0) {
      output.WriteMessageArray(6, field_names[2], blocks_);
    }
    UnknownFields.WriteTo(output);
  }
  
  private int memoizedSerializedSize = -1;
  public override int SerializedSize {
    get {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
      
      size = 0;
      if (hasText) {
        size += pb::CodedOutputStream.ComputeStringSize(1, Text);
      }
      if (hasUid) {
        size += pb::CodedOutputStream.ComputeInt64Size(2, Uid);
      }
      if (hasX) {
        size += pb::CodedOutputStream.ComputeInt32Size(3, X);
      }
      if (hasY) {
        size += pb::CodedOutputStream.ComputeInt32Size(4, Y);
      }
      foreach (global::Connection element in ConnectionsList) {
        size += pb::CodedOutputStream.ComputeMessageSize(5, element);
      }
      foreach (global::StatusBlockProtocol element in BlocksList) {
        size += pb::CodedOutputStream.ComputeMessageSize(6, element);
      }
      size += UnknownFields.SerializedSize;
      memoizedSerializedSize = size;
      return size;
    }
  }
  
  public static ConversationNode ParseFrom(pb::ByteString data) {
    return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
  }
  public static ConversationNode ParseFrom(pb::ByteString data, pb::ExtensionRegistry extensionRegistry) {
    return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
  }
  public static ConversationNode ParseFrom(byte[] data) {
    return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
  }
  public static ConversationNode ParseFrom(byte[] data, pb::ExtensionRegistry extensionRegistry) {
    return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
  }
  public static ConversationNode ParseFrom(global::System.IO.Stream input) {
    return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
  }
  public static ConversationNode ParseFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
    return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
  }
  public static ConversationNode ParseDelimitedFrom(global::System.IO.Stream input) {
    return CreateBuilder().MergeDelimitedFrom(input).BuildParsed();
  }
  public static ConversationNode ParseDelimitedFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
    return CreateBuilder().MergeDelimitedFrom(input, extensionRegistry).BuildParsed();
  }
  public static ConversationNode ParseFrom(pb::ICodedInputStream input) {
    return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
  }
  public static ConversationNode ParseFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
    return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
  }
  private ConversationNode MakeReadOnly() {
    connections_.MakeReadOnly();
    blocks_.MakeReadOnly();
    return this;
  }
  
  public static Builder CreateBuilder() { return new Builder(); }
  public override Builder ToBuilder() { return CreateBuilder(this); }
  public override Builder CreateBuilderForType() { return new Builder(); }
  public static Builder CreateBuilder(ConversationNode prototype) {
    return new Builder(prototype);
  }
  
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class Builder : pb::GeneratedBuilder<ConversationNode, Builder> {
    protected override Builder ThisBuilder {
      get { return this; }
    }
    public Builder() {
      result = DefaultInstance;
      resultIsReadOnly = true;
    }
    internal Builder(ConversationNode cloneFrom) {
      result = cloneFrom;
      resultIsReadOnly = true;
    }
    
    private bool resultIsReadOnly;
    private ConversationNode result;
    
    private ConversationNode PrepareBuilder() {
      if (resultIsReadOnly) {
        ConversationNode original = result;
        result = new ConversationNode();
        resultIsReadOnly = false;
        MergeFrom(original);
      }
      return result;
    }
    
    public override bool IsInitialized {
      get { return result.IsInitialized; }
    }
    
    protected override ConversationNode MessageBeingBuilt {
      get { return PrepareBuilder(); }
    }
    
    public override Builder Clear() {
      result = DefaultInstance;
      resultIsReadOnly = true;
      return this;
    }
    
    public override Builder Clone() {
      if (resultIsReadOnly) {
        return new Builder(result);
      } else {
        return new Builder().MergeFrom(result);
      }
    }
    
    public override pbd::MessageDescriptor DescriptorForType {
      get { return global::ConversationNode.Descriptor; }
    }
    
    public override ConversationNode DefaultInstanceForType {
      get { return global::ConversationNode.DefaultInstance; }
    }
    
    public override ConversationNode BuildPartial() {
      if (resultIsReadOnly) {
        return result;
      }
      resultIsReadOnly = true;
      return result.MakeReadOnly();
    }
    
    public override Builder MergeFrom(pb::IMessage other) {
      if (other is ConversationNode) {
        return MergeFrom((ConversationNode) other);
      } else {
        base.MergeFrom(other);
        return this;
      }
    }
    
    public override Builder MergeFrom(ConversationNode other) {
      if (other == global::ConversationNode.DefaultInstance) return this;
      PrepareBuilder();
      if (other.HasText) {
        Text = other.Text;
      }
      if (other.HasUid) {
        Uid = other.Uid;
      }
      if (other.HasX) {
        X = other.X;
      }
      if (other.HasY) {
        Y = other.Y;
      }
      if (other.connections_.Count != 0) {
        result.connections_.Add(other.connections_);
      }
      if (other.blocks_.Count != 0) {
        result.blocks_.Add(other.blocks_);
      }
      this.MergeUnknownFields(other.UnknownFields);
      return this;
    }
    
    public override Builder MergeFrom(pb::ICodedInputStream input) {
      return MergeFrom(input, pb::ExtensionRegistry.Empty);
    }
    
    public override Builder MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
      PrepareBuilder();
      pb::UnknownFieldSet.Builder unknownFields = null;
      uint tag;
      string field_name;
      while (input.ReadTag(out tag, out field_name)) {
        if(tag == 0 && field_name != null) {
          int field_ordinal = global::System.Array.BinarySearch(_conversationNodeFieldNames, field_name, global::System.StringComparer.Ordinal);
          if(field_ordinal >= 0)
            tag = _conversationNodeFieldTags[field_ordinal];
          else {
            if (unknownFields == null) {
              unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
            }
            ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
            continue;
          }
        }
        switch (tag) {
          case 0: {
            throw pb::InvalidProtocolBufferException.InvalidTag();
          }
          default: {
            if (pb::WireFormat.IsEndGroupTag(tag)) {
              if (unknownFields != null) {
                this.UnknownFields = unknownFields.Build();
              }
              return this;
            }
            if (unknownFields == null) {
              unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
            }
            ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
            break;
          }
          case 10: {
            result.hasText = input.ReadString(ref result.text_);
            break;
          }
          case 16: {
            result.hasUid = input.ReadInt64(ref result.uid_);
            break;
          }
          case 24: {
            result.hasX = input.ReadInt32(ref result.x_);
            break;
          }
          case 32: {
            result.hasY = input.ReadInt32(ref result.y_);
            break;
          }
          case 42: {
            input.ReadMessageArray(tag, field_name, result.connections_, global::Connection.DefaultInstance, extensionRegistry);
            break;
          }
          case 50: {
            input.ReadMessageArray(tag, field_name, result.blocks_, global::StatusBlockProtocol.DefaultInstance, extensionRegistry);
            break;
          }
        }
      }
      
      if (unknownFields != null) {
        this.UnknownFields = unknownFields.Build();
      }
      return this;
    }
    
    
    public bool HasText {
      get { return result.hasText; }
    }
    public string Text {
      get { return result.Text; }
      set { SetText(value); }
    }
    public Builder SetText(string value) {
      pb::ThrowHelper.ThrowIfNull(value, "value");
      PrepareBuilder();
      result.hasText = true;
      result.text_ = value;
      return this;
    }
    public Builder ClearText() {
      PrepareBuilder();
      result.hasText = false;
      result.text_ = "";
      return this;
    }
    
    public bool HasUid {
      get { return result.hasUid; }
    }
    public long Uid {
      get { return result.Uid; }
      set { SetUid(value); }
    }
    public Builder SetUid(long value) {
      PrepareBuilder();
      result.hasUid = true;
      result.uid_ = value;
      return this;
    }
    public Builder ClearUid() {
      PrepareBuilder();
      result.hasUid = false;
      result.uid_ = 0L;
      return this;
    }
    
    public bool HasX {
      get { return result.hasX; }
    }
    public int X {
      get { return result.X; }
      set { SetX(value); }
    }
    public Builder SetX(int value) {
      PrepareBuilder();
      result.hasX = true;
      result.x_ = value;
      return this;
    }
    public Builder ClearX() {
      PrepareBuilder();
      result.hasX = false;
      result.x_ = 0;
      return this;
    }
    
    public bool HasY {
      get { return result.hasY; }
    }
    public int Y {
      get { return result.Y; }
      set { SetY(value); }
    }
    public Builder SetY(int value) {
      PrepareBuilder();
      result.hasY = true;
      result.y_ = value;
      return this;
    }
    public Builder ClearY() {
      PrepareBuilder();
      result.hasY = false;
      result.y_ = 0;
      return this;
    }
    
    public pbc::IPopsicleList<global::Connection> ConnectionsList {
      get { return PrepareBuilder().connections_; }
    }
    public int ConnectionsCount {
      get { return result.ConnectionsCount; }
    }
    public global::Connection GetConnections(int index) {
      return result.GetConnections(index);
    }
    public Builder SetConnections(int index, global::Connection value) {
      pb::ThrowHelper.ThrowIfNull(value, "value");
      PrepareBuilder();
      result.connections_[index] = value;
      return this;
    }
    public Builder SetConnections(int index, global::Connection.Builder builderForValue) {
      pb::ThrowHelper.ThrowIfNull(builderForValue, "builderForValue");
      PrepareBuilder();
      result.connections_[index] = builderForValue.Build();
      return this;
    }
    public Builder AddConnections(global::Connection value) {
      pb::ThrowHelper.ThrowIfNull(value, "value");
      PrepareBuilder();
      result.connections_.Add(value);
      return this;
    }
    public Builder AddConnections(global::Connection.Builder builderForValue) {
      pb::ThrowHelper.ThrowIfNull(builderForValue, "builderForValue");
      PrepareBuilder();
      result.connections_.Add(builderForValue.Build());
      return this;
    }
    public Builder AddRangeConnections(scg::IEnumerable<global::Connection> values) {
      PrepareBuilder();
      result.connections_.Add(values);
      return this;
    }
    public Builder ClearConnections() {
      PrepareBuilder();
      result.connections_.Clear();
      return this;
    }
    
    public pbc::IPopsicleList<global::StatusBlockProtocol> BlocksList {
      get { return PrepareBuilder().blocks_; }
    }
    public int BlocksCount {
      get { return result.BlocksCount; }
    }
    public global::StatusBlockProtocol GetBlocks(int index) {
      return result.GetBlocks(index);
    }
    public Builder SetBlocks(int index, global::StatusBlockProtocol value) {
      pb::ThrowHelper.ThrowIfNull(value, "value");
      PrepareBuilder();
      result.blocks_[index] = value;
      return this;
    }
    public Builder SetBlocks(int index, global::StatusBlockProtocol.Builder builderForValue) {
      pb::ThrowHelper.ThrowIfNull(builderForValue, "builderForValue");
      PrepareBuilder();
      result.blocks_[index] = builderForValue.Build();
      return this;
    }
    public Builder AddBlocks(global::StatusBlockProtocol value) {
      pb::ThrowHelper.ThrowIfNull(value, "value");
      PrepareBuilder();
      result.blocks_.Add(value);
      return this;
    }
    public Builder AddBlocks(global::StatusBlockProtocol.Builder builderForValue) {
      pb::ThrowHelper.ThrowIfNull(builderForValue, "builderForValue");
      PrepareBuilder();
      result.blocks_.Add(builderForValue.Build());
      return this;
    }
    public Builder AddRangeBlocks(scg::IEnumerable<global::StatusBlockProtocol> values) {
      PrepareBuilder();
      result.blocks_.Add(values);
      return this;
    }
    public Builder ClearBlocks() {
      PrepareBuilder();
      result.blocks_.Clear();
      return this;
    }
  }
  static ConversationNode() {
    object.ReferenceEquals(global::ConversationProtobuf.Descriptor, null);
  }
}

[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
public sealed partial class Connection : pb::GeneratedMessage<Connection, Connection.Builder> {
  private Connection() { }
  private static readonly Connection defaultInstance = new Connection().MakeReadOnly();
  private static readonly string[] _connectionFieldNames = new string[] { "nodeId", "requirementSets", "text" };
  private static readonly uint[] _connectionFieldTags = new uint[] { 8, 26, 18 };
  public static Connection DefaultInstance {
    get { return defaultInstance; }
  }
  
  public override Connection DefaultInstanceForType {
    get { return DefaultInstance; }
  }
  
  protected override Connection ThisMessage {
    get { return this; }
  }
  
  public static pbd::MessageDescriptor Descriptor {
    get { return global::ConversationProtobuf.internal__static_Connection__Descriptor; }
  }
  
  protected override pb::FieldAccess.FieldAccessorTable<Connection, Connection.Builder> InternalFieldAccessors {
    get { return global::ConversationProtobuf.internal__static_Connection__FieldAccessorTable; }
  }
  
  public const int NodeIdFieldNumber = 1;
  private bool hasNodeId;
  private long nodeId_;
  public bool HasNodeId {
    get { return hasNodeId; }
  }
  public long NodeId {
    get { return nodeId_; }
  }
  
  public const int TextFieldNumber = 2;
  private bool hasText;
  private string text_ = "";
  public bool HasText {
    get { return hasText; }
  }
  public string Text {
    get { return text_; }
  }
  
  public const int RequirementSetsFieldNumber = 3;
  private pbc::PopsicleList<global::RequirementSet> requirementSets_ = new pbc::PopsicleList<global::RequirementSet>();
  public scg::IList<global::RequirementSet> RequirementSetsList {
    get { return requirementSets_; }
  }
  public int RequirementSetsCount {
    get { return requirementSets_.Count; }
  }
  public global::RequirementSet GetRequirementSets(int index) {
    return requirementSets_[index];
  }
  
  public override bool IsInitialized {
    get {
      if (!hasNodeId) return false;
      if (!hasText) return false;
      foreach (global::RequirementSet element in RequirementSetsList) {
        if (!element.IsInitialized) return false;
      }
      return true;
    }
  }
  
  public override void WriteTo(pb::ICodedOutputStream output) {
    int size = SerializedSize;
    string[] field_names = _connectionFieldNames;
    if (hasNodeId) {
      output.WriteInt64(1, field_names[0], NodeId);
    }
    if (hasText) {
      output.WriteString(2, field_names[2], Text);
    }
    if (requirementSets_.Count > 0) {
      output.WriteMessageArray(3, field_names[1], requirementSets_);
    }
    UnknownFields.WriteTo(output);
  }
  
  private int memoizedSerializedSize = -1;
  public override int SerializedSize {
    get {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
      
      size = 0;
      if (hasNodeId) {
        size += pb::CodedOutputStream.ComputeInt64Size(1, NodeId);
      }
      if (hasText) {
        size += pb::CodedOutputStream.ComputeStringSize(2, Text);
      }
      foreach (global::RequirementSet element in RequirementSetsList) {
        size += pb::CodedOutputStream.ComputeMessageSize(3, element);
      }
      size += UnknownFields.SerializedSize;
      memoizedSerializedSize = size;
      return size;
    }
  }
  
  public static Connection ParseFrom(pb::ByteString data) {
    return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
  }
  public static Connection ParseFrom(pb::ByteString data, pb::ExtensionRegistry extensionRegistry) {
    return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
  }
  public static Connection ParseFrom(byte[] data) {
    return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
  }
  public static Connection ParseFrom(byte[] data, pb::ExtensionRegistry extensionRegistry) {
    return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
  }
  public static Connection ParseFrom(global::System.IO.Stream input) {
    return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
  }
  public static Connection ParseFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
    return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
  }
  public static Connection ParseDelimitedFrom(global::System.IO.Stream input) {
    return CreateBuilder().MergeDelimitedFrom(input).BuildParsed();
  }
  public static Connection ParseDelimitedFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
    return CreateBuilder().MergeDelimitedFrom(input, extensionRegistry).BuildParsed();
  }
  public static Connection ParseFrom(pb::ICodedInputStream input) {
    return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
  }
  public static Connection ParseFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
    return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
  }
  private Connection MakeReadOnly() {
    requirementSets_.MakeReadOnly();
    return this;
  }
  
  public static Builder CreateBuilder() { return new Builder(); }
  public override Builder ToBuilder() { return CreateBuilder(this); }
  public override Builder CreateBuilderForType() { return new Builder(); }
  public static Builder CreateBuilder(Connection prototype) {
    return new Builder(prototype);
  }
  
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class Builder : pb::GeneratedBuilder<Connection, Builder> {
    protected override Builder ThisBuilder {
      get { return this; }
    }
    public Builder() {
      result = DefaultInstance;
      resultIsReadOnly = true;
    }
    internal Builder(Connection cloneFrom) {
      result = cloneFrom;
      resultIsReadOnly = true;
    }
    
    private bool resultIsReadOnly;
    private Connection result;
    
    private Connection PrepareBuilder() {
      if (resultIsReadOnly) {
        Connection original = result;
        result = new Connection();
        resultIsReadOnly = false;
        MergeFrom(original);
      }
      return result;
    }
    
    public override bool IsInitialized {
      get { return result.IsInitialized; }
    }
    
    protected override Connection MessageBeingBuilt {
      get { return PrepareBuilder(); }
    }
    
    public override Builder Clear() {
      result = DefaultInstance;
      resultIsReadOnly = true;
      return this;
    }
    
    public override Builder Clone() {
      if (resultIsReadOnly) {
        return new Builder(result);
      } else {
        return new Builder().MergeFrom(result);
      }
    }
    
    public override pbd::MessageDescriptor DescriptorForType {
      get { return global::Connection.Descriptor; }
    }
    
    public override Connection DefaultInstanceForType {
      get { return global::Connection.DefaultInstance; }
    }
    
    public override Connection BuildPartial() {
      if (resultIsReadOnly) {
        return result;
      }
      resultIsReadOnly = true;
      return result.MakeReadOnly();
    }
    
    public override Builder MergeFrom(pb::IMessage other) {
      if (other is Connection) {
        return MergeFrom((Connection) other);
      } else {
        base.MergeFrom(other);
        return this;
      }
    }
    
    public override Builder MergeFrom(Connection other) {
      if (other == global::Connection.DefaultInstance) return this;
      PrepareBuilder();
      if (other.HasNodeId) {
        NodeId = other.NodeId;
      }
      if (other.HasText) {
        Text = other.Text;
      }
      if (other.requirementSets_.Count != 0) {
        result.requirementSets_.Add(other.requirementSets_);
      }
      this.MergeUnknownFields(other.UnknownFields);
      return this;
    }
    
    public override Builder MergeFrom(pb::ICodedInputStream input) {
      return MergeFrom(input, pb::ExtensionRegistry.Empty);
    }
    
    public override Builder MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
      PrepareBuilder();
      pb::UnknownFieldSet.Builder unknownFields = null;
      uint tag;
      string field_name;
      while (input.ReadTag(out tag, out field_name)) {
        if(tag == 0 && field_name != null) {
          int field_ordinal = global::System.Array.BinarySearch(_connectionFieldNames, field_name, global::System.StringComparer.Ordinal);
          if(field_ordinal >= 0)
            tag = _connectionFieldTags[field_ordinal];
          else {
            if (unknownFields == null) {
              unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
            }
            ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
            continue;
          }
        }
        switch (tag) {
          case 0: {
            throw pb::InvalidProtocolBufferException.InvalidTag();
          }
          default: {
            if (pb::WireFormat.IsEndGroupTag(tag)) {
              if (unknownFields != null) {
                this.UnknownFields = unknownFields.Build();
              }
              return this;
            }
            if (unknownFields == null) {
              unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
            }
            ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
            break;
          }
          case 8: {
            result.hasNodeId = input.ReadInt64(ref result.nodeId_);
            break;
          }
          case 18: {
            result.hasText = input.ReadString(ref result.text_);
            break;
          }
          case 26: {
            input.ReadMessageArray(tag, field_name, result.requirementSets_, global::RequirementSet.DefaultInstance, extensionRegistry);
            break;
          }
        }
      }
      
      if (unknownFields != null) {
        this.UnknownFields = unknownFields.Build();
      }
      return this;
    }
    
    
    public bool HasNodeId {
      get { return result.hasNodeId; }
    }
    public long NodeId {
      get { return result.NodeId; }
      set { SetNodeId(value); }
    }
    public Builder SetNodeId(long value) {
      PrepareBuilder();
      result.hasNodeId = true;
      result.nodeId_ = value;
      return this;
    }
    public Builder ClearNodeId() {
      PrepareBuilder();
      result.hasNodeId = false;
      result.nodeId_ = 0L;
      return this;
    }
    
    public bool HasText {
      get { return result.hasText; }
    }
    public string Text {
      get { return result.Text; }
      set { SetText(value); }
    }
    public Builder SetText(string value) {
      pb::ThrowHelper.ThrowIfNull(value, "value");
      PrepareBuilder();
      result.hasText = true;
      result.text_ = value;
      return this;
    }
    public Builder ClearText() {
      PrepareBuilder();
      result.hasText = false;
      result.text_ = "";
      return this;
    }
    
    public pbc::IPopsicleList<global::RequirementSet> RequirementSetsList {
      get { return PrepareBuilder().requirementSets_; }
    }
    public int RequirementSetsCount {
      get { return result.RequirementSetsCount; }
    }
    public global::RequirementSet GetRequirementSets(int index) {
      return result.GetRequirementSets(index);
    }
    public Builder SetRequirementSets(int index, global::RequirementSet value) {
      pb::ThrowHelper.ThrowIfNull(value, "value");
      PrepareBuilder();
      result.requirementSets_[index] = value;
      return this;
    }
    public Builder SetRequirementSets(int index, global::RequirementSet.Builder builderForValue) {
      pb::ThrowHelper.ThrowIfNull(builderForValue, "builderForValue");
      PrepareBuilder();
      result.requirementSets_[index] = builderForValue.Build();
      return this;
    }
    public Builder AddRequirementSets(global::RequirementSet value) {
      pb::ThrowHelper.ThrowIfNull(value, "value");
      PrepareBuilder();
      result.requirementSets_.Add(value);
      return this;
    }
    public Builder AddRequirementSets(global::RequirementSet.Builder builderForValue) {
      pb::ThrowHelper.ThrowIfNull(builderForValue, "builderForValue");
      PrepareBuilder();
      result.requirementSets_.Add(builderForValue.Build());
      return this;
    }
    public Builder AddRangeRequirementSets(scg::IEnumerable<global::RequirementSet> values) {
      PrepareBuilder();
      result.requirementSets_.Add(values);
      return this;
    }
    public Builder ClearRequirementSets() {
      PrepareBuilder();
      result.requirementSets_.Clear();
      return this;
    }
  }
  static Connection() {
    object.ReferenceEquals(global::ConversationProtobuf.Descriptor, null);
  }
}

[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
public sealed partial class RequirementSet : pb::GeneratedMessage<RequirementSet, RequirementSet.Builder> {
  private RequirementSet() { }
  private static readonly RequirementSet defaultInstance = new RequirementSet().MakeReadOnly();
  private static readonly string[] _requirementSetFieldNames = new string[] { "requirements" };
  private static readonly uint[] _requirementSetFieldTags = new uint[] { 10 };
  public static RequirementSet DefaultInstance {
    get { return defaultInstance; }
  }
  
  public override RequirementSet DefaultInstanceForType {
    get { return DefaultInstance; }
  }
  
  protected override RequirementSet ThisMessage {
    get { return this; }
  }
  
  public static pbd::MessageDescriptor Descriptor {
    get { return global::ConversationProtobuf.internal__static_RequirementSet__Descriptor; }
  }
  
  protected override pb::FieldAccess.FieldAccessorTable<RequirementSet, RequirementSet.Builder> InternalFieldAccessors {
    get { return global::ConversationProtobuf.internal__static_RequirementSet__FieldAccessorTable; }
  }
  
  public const int RequirementsFieldNumber = 1;
  private pbc::PopsicleList<global::StatusCheckableProtocol> requirements_ = new pbc::PopsicleList<global::StatusCheckableProtocol>();
  public scg::IList<global::StatusCheckableProtocol> RequirementsList {
    get { return requirements_; }
  }
  public int RequirementsCount {
    get { return requirements_.Count; }
  }
  public global::StatusCheckableProtocol GetRequirements(int index) {
    return requirements_[index];
  }
  
  public override bool IsInitialized {
    get {
      foreach (global::StatusCheckableProtocol element in RequirementsList) {
        if (!element.IsInitialized) return false;
      }
      return true;
    }
  }
  
  public override void WriteTo(pb::ICodedOutputStream output) {
    int size = SerializedSize;
    string[] field_names = _requirementSetFieldNames;
    if (requirements_.Count > 0) {
      output.WriteMessageArray(1, field_names[0], requirements_);
    }
    UnknownFields.WriteTo(output);
  }
  
  private int memoizedSerializedSize = -1;
  public override int SerializedSize {
    get {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
      
      size = 0;
      foreach (global::StatusCheckableProtocol element in RequirementsList) {
        size += pb::CodedOutputStream.ComputeMessageSize(1, element);
      }
      size += UnknownFields.SerializedSize;
      memoizedSerializedSize = size;
      return size;
    }
  }
  
  public static RequirementSet ParseFrom(pb::ByteString data) {
    return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
  }
  public static RequirementSet ParseFrom(pb::ByteString data, pb::ExtensionRegistry extensionRegistry) {
    return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
  }
  public static RequirementSet ParseFrom(byte[] data) {
    return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
  }
  public static RequirementSet ParseFrom(byte[] data, pb::ExtensionRegistry extensionRegistry) {
    return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
  }
  public static RequirementSet ParseFrom(global::System.IO.Stream input) {
    return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
  }
  public static RequirementSet ParseFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
    return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
  }
  public static RequirementSet ParseDelimitedFrom(global::System.IO.Stream input) {
    return CreateBuilder().MergeDelimitedFrom(input).BuildParsed();
  }
  public static RequirementSet ParseDelimitedFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
    return CreateBuilder().MergeDelimitedFrom(input, extensionRegistry).BuildParsed();
  }
  public static RequirementSet ParseFrom(pb::ICodedInputStream input) {
    return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
  }
  public static RequirementSet ParseFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
    return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
  }
  private RequirementSet MakeReadOnly() {
    requirements_.MakeReadOnly();
    return this;
  }
  
  public static Builder CreateBuilder() { return new Builder(); }
  public override Builder ToBuilder() { return CreateBuilder(this); }
  public override Builder CreateBuilderForType() { return new Builder(); }
  public static Builder CreateBuilder(RequirementSet prototype) {
    return new Builder(prototype);
  }
  
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class Builder : pb::GeneratedBuilder<RequirementSet, Builder> {
    protected override Builder ThisBuilder {
      get { return this; }
    }
    public Builder() {
      result = DefaultInstance;
      resultIsReadOnly = true;
    }
    internal Builder(RequirementSet cloneFrom) {
      result = cloneFrom;
      resultIsReadOnly = true;
    }
    
    private bool resultIsReadOnly;
    private RequirementSet result;
    
    private RequirementSet PrepareBuilder() {
      if (resultIsReadOnly) {
        RequirementSet original = result;
        result = new RequirementSet();
        resultIsReadOnly = false;
        MergeFrom(original);
      }
      return result;
    }
    
    public override bool IsInitialized {
      get { return result.IsInitialized; }
    }
    
    protected override RequirementSet MessageBeingBuilt {
      get { return PrepareBuilder(); }
    }
    
    public override Builder Clear() {
      result = DefaultInstance;
      resultIsReadOnly = true;
      return this;
    }
    
    public override Builder Clone() {
      if (resultIsReadOnly) {
        return new Builder(result);
      } else {
        return new Builder().MergeFrom(result);
      }
    }
    
    public override pbd::MessageDescriptor DescriptorForType {
      get { return global::RequirementSet.Descriptor; }
    }
    
    public override RequirementSet DefaultInstanceForType {
      get { return global::RequirementSet.DefaultInstance; }
    }
    
    public override RequirementSet BuildPartial() {
      if (resultIsReadOnly) {
        return result;
      }
      resultIsReadOnly = true;
      return result.MakeReadOnly();
    }
    
    public override Builder MergeFrom(pb::IMessage other) {
      if (other is RequirementSet) {
        return MergeFrom((RequirementSet) other);
      } else {
        base.MergeFrom(other);
        return this;
      }
    }
    
    public override Builder MergeFrom(RequirementSet other) {
      if (other == global::RequirementSet.DefaultInstance) return this;
      PrepareBuilder();
      if (other.requirements_.Count != 0) {
        result.requirements_.Add(other.requirements_);
      }
      this.MergeUnknownFields(other.UnknownFields);
      return this;
    }
    
    public override Builder MergeFrom(pb::ICodedInputStream input) {
      return MergeFrom(input, pb::ExtensionRegistry.Empty);
    }
    
    public override Builder MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
      PrepareBuilder();
      pb::UnknownFieldSet.Builder unknownFields = null;
      uint tag;
      string field_name;
      while (input.ReadTag(out tag, out field_name)) {
        if(tag == 0 && field_name != null) {
          int field_ordinal = global::System.Array.BinarySearch(_requirementSetFieldNames, field_name, global::System.StringComparer.Ordinal);
          if(field_ordinal >= 0)
            tag = _requirementSetFieldTags[field_ordinal];
          else {
            if (unknownFields == null) {
              unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
            }
            ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
            continue;
          }
        }
        switch (tag) {
          case 0: {
            throw pb::InvalidProtocolBufferException.InvalidTag();
          }
          default: {
            if (pb::WireFormat.IsEndGroupTag(tag)) {
              if (unknownFields != null) {
                this.UnknownFields = unknownFields.Build();
              }
              return this;
            }
            if (unknownFields == null) {
              unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
            }
            ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
            break;
          }
          case 10: {
            input.ReadMessageArray(tag, field_name, result.requirements_, global::StatusCheckableProtocol.DefaultInstance, extensionRegistry);
            break;
          }
        }
      }
      
      if (unknownFields != null) {
        this.UnknownFields = unknownFields.Build();
      }
      return this;
    }
    
    
    public pbc::IPopsicleList<global::StatusCheckableProtocol> RequirementsList {
      get { return PrepareBuilder().requirements_; }
    }
    public int RequirementsCount {
      get { return result.RequirementsCount; }
    }
    public global::StatusCheckableProtocol GetRequirements(int index) {
      return result.GetRequirements(index);
    }
    public Builder SetRequirements(int index, global::StatusCheckableProtocol value) {
      pb::ThrowHelper.ThrowIfNull(value, "value");
      PrepareBuilder();
      result.requirements_[index] = value;
      return this;
    }
    public Builder SetRequirements(int index, global::StatusCheckableProtocol.Builder builderForValue) {
      pb::ThrowHelper.ThrowIfNull(builderForValue, "builderForValue");
      PrepareBuilder();
      result.requirements_[index] = builderForValue.Build();
      return this;
    }
    public Builder AddRequirements(global::StatusCheckableProtocol value) {
      pb::ThrowHelper.ThrowIfNull(value, "value");
      PrepareBuilder();
      result.requirements_.Add(value);
      return this;
    }
    public Builder AddRequirements(global::StatusCheckableProtocol.Builder builderForValue) {
      pb::ThrowHelper.ThrowIfNull(builderForValue, "builderForValue");
      PrepareBuilder();
      result.requirements_.Add(builderForValue.Build());
      return this;
    }
    public Builder AddRangeRequirements(scg::IEnumerable<global::StatusCheckableProtocol> values) {
      PrepareBuilder();
      result.requirements_.Add(values);
      return this;
    }
    public Builder ClearRequirements() {
      PrepareBuilder();
      result.requirements_.Clear();
      return this;
    }
  }
  static RequirementSet() {
    object.ReferenceEquals(global::ConversationProtobuf.Descriptor, null);
  }
}

#endregion


#endregion Designer generated code
