using UnityEngine;
using System.Collections;
using System.Collections.Generic;

public class Area
{

    #region Plans

    //TODO: Add booleans representing whether or not this Area has been generated, is being shown, or is
        //currently being generated by a thread. (Also have a refence to the thread, to kill it, if need be.)

    //TODO: Add a 2d array of Tiles, which will be this Area.

    //TODO: This Area will also need references to all of the enemies and objects in this Area. To kill them.

    //TODO: Multithreaded Area generation, when the player is in an adjacent Area. To reduce load times.

    //TODO: Create a function that randomly assigns a quest to one of its Rooms.
    
    //Plans: To generate the Area, first generate the rooms, and place them into the 2d tile array.
                //Then, genereate a 2d array of int values, which will function as weights.
                //While all rooms are not connected.
                    //Use an A* algorithm to create corridors from Room to Room.
    //Once all rooms are connected, generate decorations/enemies/Quest material in each room.

    #endregion


    #region Variables

    private AreaType type;

    //Areas which this Area is connected to. True, if connected to an area in that direction.
    public bool north;
    public bool east;
    public bool south;
    public bool west;

    //This area's position on the map.
    public Point position
    {
        get;
        private set;
    }

    AreaGroup group;
    
    //The Map which this Area is a part of.
    Map parentMap;

    private List<Room> rooms; //The rooms which this Area contains.

    #endregion


    #region Constructors

    public Area(Map parentMap, Point position, bool N, bool E, bool S, bool W)
    {
        this.parentMap = parentMap;
        this.position = position;

        north = N;
        east = E;
        south = S;
        west = W;

        rooms = new List<Room>();

    }

    #endregion


    #region Generation methods

    //Generates the information needed to show this area.
    public void generateArea()
    {
        //(WE NEED TO DISCUSS THIS BEFORE ANYONE IMPLEMENTS IT)

        //TODO: Implement this method.

        //Should create a 2D array of some Object, probably a tile object.

        //Will have a switch statement, determining which tileset to use. Possibly which mapGenerator to use, if we
            //want to have Area's generated differently.
    }

    public void showArea()
    {
        //(WE NEED TO DISCUSS THIS BEFORE ANYONE IMPLEMENTS IT)

        //TODO: Implement this method.

        //Should take the 2D array generated by the generateArea method, create gameObjects out of them,
            //and display them to the player.

        //Probably should keep a list of these gameObjects, so that they may be destroyed.

        //Will have a switch statement determining which tileset to use for the gameObjects.
    }

    public void hideArea()
    {
        //Should (Destroy or hide? Make a separate function for destroying?) all gameObjects 
        //that were generated by this Area.
    }

    public void releaseData()
    {
        //Should null the 2D arrays of information, so that they may be garbage collected.
        //Prevents running out of RAM.
    }

    #endregion


    #region Public methods

    //Returns the neighbors connected to this Area. (Should always have at least one)
    public Area[] getNeighbors()
    {
        Area[] temp = new Area[connections()];

        int i = 0;

        if (north && parentMap.withinMapBounds(position.up))
        {
            temp[i] = parentMap.getArea(position.up);
            i++;
        }
        if (east && parentMap.withinMapBounds(position.right))
        {
            temp[i] = parentMap.getArea(position.right);
            i++;
        }
        if (south && parentMap.withinMapBounds(position.down))
        {
            temp[i] = parentMap.getArea(position.down);
            i++;
        }
        if (west && parentMap.withinMapBounds(position.left))
        {
            temp[i] = parentMap.getArea(position.left);
            i++;
        }

        return temp;
    }

    public void setType(AreaType t)
    {
        type = t;
    }
    public AreaType getType()
    {
        return type;
    }

    #endregion


    #region Helper methods

    //Returns the number of connections this Area has to other Areas.
    private int connections()
    {
        return (north ? 1 : 0) + (east ? 1 : 0) + (south ? 1 : 0) + (west ? 1 : 0);
    }

    #endregion
}
